### ISSUE TITLE
Is the so-called mechanism(choose from 3 types) ignoring potential better mesh?

### ISSUE THREAD

**Issue by hackerviruer** [gt2001/generate-2D-quadrilateral-mesh-with-neural-networks-and-tree-search#1]
I noticed that there is a mechanism that automatically chooses to generate a new point or eliminate two existing points. I think this mechanism is a greedy-like one and may ignore some potential better meshes.

**Comment by gt2001** [comment]
Thanks for the reply! What you think cannot be more right. I'm working on a novel version of the mechanism: the agent will be given several (e.g. 2) chances to force the choice of generating a new point instead of the other two choices. Of course, the DOF is still far from totally giving control on this mechanism to the agent, whereas experiments reveal that such a setting can lead to an extremely long convergence time.

**Comment by gt2001** [comment]
Thanks for the reply! What you think cannot be more right. I worked on a novel version of the mechanism: the agent would be given several (e.g. 2) chances to force the choice of generating a new point instead of the other two choices. Of course, the DOF is still far from totally giving control on this mechanism to the agent, whereas experiments reveal that such a setting can lead to an extremely long convergence time. Please check the latest code. I set a one-month delay, and you may see the changes these days.
